apt:
  sources:
  - deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble main restricted 
    universe multiverse
  - deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ noble-updates main 
    restricted universe multiverse
  - deb [arch=amd64] http://security.ubuntu.com/ubuntu/ noble-security main 
    restricted universe multiverse
  packages:
  - coreutils:amd64=9.4-3ubuntu6.1
  - libk5crypto3:amd64=1.20.1-6ubuntu2.6
  - libpython3.12-minimal:amd64=3.12.3-1ubuntu0.12
  - tzdata:all=2025b-0ubuntu0.24.04.1
  - libproc2-0:amd64=2:4.0.4-4ubuntu3.2
  - dbus-system-bus-common:all=1.14.10-4ubuntu4.1
  - libglib2.0-bin:amd64=2.80.0-6ubuntu3.8
  - libxft2:amd64=2.3.6-1build1
  - libpango-1.0-0:amd64=1.52.1+ds-1build1
  - libsmartcols1:amd64=2.39.3-9ubuntu6.5
  - liblzma5:amd64=5.6.1+really5.4.5-1ubuntu0.2
  - shared-mime-info:amd64=2.4-4
  - libthai-data:all=0.1.29-2build1
  - libsasl2-2:amd64=2.1.28+dfsg1-5ubuntu3.1
  - zlib1g:amd64=1:1.3.dfsg-3.1ubuntu2.1
  - libldap2:amd64=2.6.10+dfsg-0ubuntu0.24.04.1
  - libpam-modules:amd64=1.5.3-5ubuntu5.5
  - libaudit1:amd64=1:3.1.2-2.1build1.1
  - libgssapi-krb5-2:amd64=1.20.1-6ubuntu2.6
  - libpcre2-8-0:amd64=10.42-4ubuntu2.1
  - liblzo2-2:amd64=2.10-2build4
  - libzstd1:amd64=1.5.5+dfsg2-2build1.1
  - libdb5.3t64:amd64=5.3.28+dfsg2-7
  - librsvg2-common:amd64=2.58.0+dfsg-1build1
  - libssh-4:amd64=0.10.6-2ubuntu0.4
  - libcairo-gobject2:amd64=1.18.0-3build1
  - libcrypt1:amd64=1:4.4.36-4build1
  - libdevmapper1.02.1:amd64=2:1.02.185-3ubuntu3.2
  - libjbig0:amd64=2.1-6.1ubuntu2
  - libpangoft2-1.0-0:amd64=1.52.1+ds-1build1
  - libcolord2:amd64=1.4.7-1build2
  - libpam-systemd:amd64=255.4-1ubuntu8.12
  - libgdk-pixbuf-2.0-0:amd64=2.42.10+dfsg-3ubuntu3.2
  - fonts-dejavu-mono:all=2.37-8
  - libxrender1:amd64=1:0.9.10-1.1build1
  - procps:amd64=2:4.0.4-4ubuntu3.2
  - libyaml-0-2:amd64=0.2.5-1build1
  - xkb-data:all=2.41-2ubuntu1.1
  - dbus-bin:amd64=1.14.10-4ubuntu4.1
  - libkeyutils1:amd64=1.6.3-3build1
  - dconf-gsettings-backend:amd64=0.40.0-4ubuntu0.1
  - fonts-dejavu-core:all=2.37-8
  - gir1.2-glib-2.0:amd64=2.80.0-6ubuntu3.8
  - librsvg2-2:amd64=2.58.0+dfsg-1build1
  - libbz2-1.0:amd64=1.0.8-5.1build0.1
  - libexpat1:amd64=2.6.1-2ubuntu0.4
  - libsqlite3-0:amd64=3.45.1-1ubuntu2.5
  - gtk-update-icon-cache:amd64=3.24.41-4ubuntu1.3
  - libgcrypt20:amd64=1.10.3-2build1
  - python3-gi:amd64=3.48.2-1
  - libpam0g:amd64=1.5.3-5ubuntu5.5
  - libpython3-stdlib:amd64=3.12.3-0ubuntu2.1
  - python3-minimal:amd64=3.12.3-0ubuntu2.1
  - readline-common:all=8.2-4build1
  - mount:amd64=2.39.3-9ubuntu6.5
  - libglib2.0-0t64:amd64=2.80.0-6ubuntu3.8
  - systemd:amd64=255.4-1ubuntu8.12
  - libgcc-s1:amd64=14.2.0-4ubuntu2~24.04.1
  - hicolor-icon-theme:all=0.17-2
  - libpam-modules-bin:amd64=1.5.3-5ubuntu5.5
  - libwebp7:amd64=1.3.2-0.4build3
  - libc6:amd64=2.39-0ubuntu8.7
  - libpng16-16t64:amd64=1.6.43-5ubuntu0.5
  - libcap-ng0:amd64=0.8.4-2build2
  - libgmp10:amd64=2:6.3.0+dfsg-2ubuntu6.1
  - libcups2t64:amd64=2.4.7-1.2ubuntu7.9
  - libapparmor1:amd64=4.0.1really4.0.1-0ubuntu0.24.04.5
  - libvulkan1:amd64=1.3.275.0-1build1
  - libtinfo6:amd64=6.4+20240113-1ubuntu2
  - libuuid1:amd64=2.39.3-9ubuntu6.5
  - libargon2-1:amd64=0~20190702+dfsg-4build1
  - dbus-daemon:amd64=1.14.10-4ubuntu4.1
  - libsharpyuv0:amd64=1.3.2-0.4build3
  - libudev1:amd64=255.4-1ubuntu8.12
  - media-types:all=10.1.0
  - libaudit-common:all=1:3.1.2-2.1build1.1
  - libcairo2:amd64=1.18.0-3build1
  - libepoxy0:amd64=1.5.10-1build1
  - libmount1:amd64=2.39.3-9ubuntu6.5
  - libgpg-error0:amd64=1.47-3build2.1
  - libunistring5:amd64=1.1-2build1.1
  - dconf-service:amd64=0.40.0-4ubuntu0.1
  - libavahi-common-data:amd64=0.8-13ubuntu6.1
  - libavahi-client3:amd64=0.8-13ubuntu6.1
  - libattr1:amd64=1:2.5.2-1build1.1
  - libsystemd-shared:amd64=255.4-1ubuntu8.12
  - libssl3t64:amd64=3.0.13-0ubuntu3.7
  - python3.12:amd64=3.12.3-1ubuntu0.12
  - libkrb5-3:amd64=1.20.1-6ubuntu2.6
  - dbus-session-bus-common:all=1.14.10-4ubuntu4.1
  - libbrotli1:amd64=1.1.0-2build2
  - gir1.2-freedesktop:amd64=1.80.1-1
  - libseccomp2:amd64=2.5.5-1ubuntu3.1
  - gir1.2-pango-1.0:amd64=1.52.1+ds-1build1
  - netbase:all=6.4
  - libcom-err2:amd64=1.47.0-2.4~exp1ubuntu4.1
  - python3.12-minimal:amd64=3.12.3-1ubuntu0.12
  - libidn2-0:amd64=2.3.7-2build1.1
  - libcap2:amd64=1:2.66-5ubuntu2.2
  - libjpeg-turbo8:amd64=2.1.5-2ubuntu2
  - libavahi-core7:amd64=0.8-13ubuntu6.1
  - systemd-sysv:amd64=255.4-1ubuntu8.12
  - libadwaita-1-0:amd64=1.5.0-1ubuntu2
  - libgdk-pixbuf2.0-common:all=2.42.10+dfsg-3ubuntu3.2
  - gir1.2-graphene-1.0:amd64=1.10.8-3build2
  - desktop-file-utils:amd64=0.27-2build1
  - libxi6:amd64=2:1.8.1-1build1
  - libkrb5support0:amd64=1.20.1-6ubuntu2.6
  - liblz4-1:amd64=1.9.4-1build1.1
  - file:amd64=1:5.45-3build1
  - libstemmer0d:amd64=2.2.0-4build1
  - libhogweed6t64:amd64=3.9.1-2.2build1.1
  - libxcursor1:amd64=1:1.2.1-1build1
  - libglib2.0-data:all=2.80.0-6ubuntu3.8
  - libharfbuzz-gobject0:amd64=8.3.0-2build2
  - libgtk-4-common:all=4.14.5+ds-0ubuntu0.9
  - avahi-daemon:amd64=0.8-13ubuntu6.1
  - adwaita-icon-theme:all=46.0-1
  - libcairo-script-interpreter2:amd64=1.18.0-3build1
  - liblerc4:amd64=4.0.0+ds-4ubuntu2
  - libffi8:amd64=3.4.6-1build1
  - libreadline8t64:amd64=8.2-4build1
  - librtmp1:amd64=2.4+20151223.gitfa8646d.1-2build7
  - libdeflate0:amd64=1.19-1build1.1
  - libdatrie1:amd64=0.2.13-3build1
  - libappstream5:amd64=1.0.2-1build6
  - libacl1:amd64=2.3.2-1build1.1
  - util-linux:amd64=2.39.3-9ubuntu6.5
  - libnettle8t64:amd64=3.9.1-2.2build1.1
  - libpangocairo-1.0-0:amd64=1.52.1+ds-1build1
  - gir1.2-girepository-2.0:amd64=1.80.1-1
  - libxmlb2:amd64=0.3.18-1
  - libcurl3t64-gnutls:amd64=8.5.0-2ubuntu10.8
  - dbus:amd64=1.14.10-4ubuntu4.1
  - libsystemd0:amd64=255.4-1ubuntu8.12
  - gir1.2-gtk-4.0:amd64=4.14.5+ds-0ubuntu0.9
  - libfontconfig1:amd64=2.15.0-1.1ubuntu2
  - libgraphite2-3:amd64=1.3.14-2build1
  - libxinerama1:amd64=2:1.1.4-3build1
  - libxdamage1:amd64=1:1.1.6-1build1
  - libfribidi0:amd64=1.0.13-3build1
  - libmagic1t64:amd64=1:5.45-3build1
  - fontconfig-config:amd64=2.15.0-1.1ubuntu2
  - libgdk-pixbuf2.0-bin:amd64=2.42.10+dfsg-3ubuntu3.2
  - libfdisk1:amd64=2.39.3-9ubuntu6.5
  - gir1.2-gdkpixbuf-2.0:amd64=2.42.10+dfsg-3ubuntu3.2
  - libxfixes3:amd64=1:6.0.0-2build1
  - libpangoxft-1.0-0:amd64=1.52.1+ds-1build1
  - libavahi-common3:amd64=0.8-13ubuntu6.1
  - libsasl2-modules-db:amd64=2.1.28+dfsg1-5ubuntu3.1
  - gir1.2-adw-1:amd64=1.5.0-1ubuntu2
  - libstdc++6:amd64=14.2.0-4ubuntu2~24.04.1
  - systemd-dev:all=255.4-1ubuntu8.12
  - libgnutls30t64:amd64=3.8.3-1.1ubuntu3.5
  - libthai0:amd64=0.1.29-2build1
  - libharfbuzz0b:amd64=8.3.0-2build2
  - libjpeg8:amd64=8c-2ubuntu11
  - liblcms2-2:amd64=2.14-2build1
  - libpython3.12-stdlib:amd64=3.12.3-1ubuntu0.12
  - libmagic-mgc:amd64=1:5.45-3build1
  - libcryptsetup12:amd64=2:2.7.0-1ubuntu4.2
  - libxml2:amd64=2.9.14+dfsg-1.3ubuntu3.7
  - libgraphene-1.0-0:amd64=1.10.8-3build2
  - libtasn1-6:amd64=4.19.0-3ubuntu0.24.04.2
  - libelf1t64:amd64=0.190-1.1ubuntu0.1
  - libpsl5t64:amd64=0.21.2-1.1build1
  - libfreetype6:amd64=2.13.2+dfsg-1ubuntu0.1
  - fdisk:amd64=2.39.3-9ubuntu6.5
  - fontconfig:amd64=2.15.0-1.1ubuntu2
  - libxext6:amd64=2:1.3.4-1build2
  - libxrandr2:amd64=2:1.5.2-2build1
  - libncursesw6:amd64=6.4+20240113-1ubuntu2
  - libtiff6:amd64=4.5.1+git230720-4ubuntu2.4
  - gcc-14-base:amd64=14.2.0-4ubuntu2~24.04.1
  - libkmod2:amd64=31+20240202-2ubuntu7.1
  - libdconf1:amd64=0.40.0-4ubuntu0.1
  - gir1.2-harfbuzz-0.0:amd64=8.3.0-2build2
  - libselinux1:amd64=3.5-2ubuntu2.1
  - libp11-kit0:amd64=0.25.3-4ubuntu2.1
  - libgtk-4-1:amd64=4.14.5+ds-0ubuntu0.9
  - squashfs-tools:amd64=1:4.6.1-1build1
  - dbus-user-session:amd64=1.14.10-4ubuntu4.1
  - libicu74:amd64=74.2-1ubuntu3.1
  - libpam-runtime:all=1.5.3-5ubuntu5.5
  - libblkid1:amd64=2.39.3-9ubuntu6.5
  - libxkbcommon0:amd64=1.6.0-1build1
  - libnghttp2-14:amd64=1.59.0-1ubuntu0.2
  - libgirepository-1.0-1:amd64=1.80.1-1
  - libjson-c5:amd64=0.17-1build1
  - python3:amd64=3.12.3-0ubuntu2.1
  - libdaemon0:amd64=0.14-7.1ubuntu4
  - libdbus-1-3:amd64=1.14.10-4ubuntu4.1
  - libcap2-bin:amd64=1:2.66-5ubuntu2.2
  - libpixman-1-0:amd64=0.42.2-1build1
