Dir "/work/appimage-build/apt";
Dir::State "/work/appimage-build/apt";
Dir::Cache "/work/appimage-build/apt";
Dir::Etc::Main "/work/appimage-build/apt/apt.conf";
Dir::Etc::Parts "/work/appimage-build/apt/apt.conf.d";
Dir::Etc::SourceList "/work/appimage-build/apt/sources.list";
Dir::Etc::SourceListParts "/work/appimage-build/apt/sources.list.d";
Dir::Etc::PreferencesParts "/work/appimage-build/apt/preferences.d";
Dir::Etc::TrustedParts "/work/appimage-build/apt/keys";
Dir::State::status "/work/appimage-build/apt/dpkg/status";
Dir::Ignore-Files-Silently False;
APT::Install-Recommends False;
APT::Install-Suggests False;
APT::Immediate-Configure False;
APT::Architecture "amd64";
APT::Architectures {"amd64"; }
Acquire::Languages "none";
APT::Get::AllowUnauthenticated False;
Acquire::AllowInsecureRepositories False;
